export const siteConfig = {
  name: "Ashu Kumar",
  title: "Senior Frontend Engineer",
  headline:
    "React.js · Next.js · TypeScript · UI Architecture · Design Systems · Performance · Accessibility",
  description:
    "Senior Frontend Engineer with 10+ years designing and developing scalable, responsive, and high-performance web applications. Specialized in React.js, Next.js, TypeScript, design systems, Core Web Vitals, WCAG accessibility, and AI-assisted development.",
  url: "https://ashukumar.dev",
  ogImage: "/og-image.png",
  email: "ashuty114@gmail.com",
  phone: "+91-9310581784",
  location: "Delhi/NCR, India",
  linkedin: "https://www.linkedin.com/in/ashutyagi-se",
  accent: "#2563EB",
  keywords: [
    "Senior Frontend Engineer",
    "React.js",
    "Next.js",
    "TypeScript",
    "UI Architecture",
    "Design Systems",
    "Component Libraries",
    "Core Web Vitals",
    "Accessibility",
    "WCAG",
    "Figma to Code",
    "Storybook",
    "AI-Assisted Development",
    "Apollo 24|7",
    "Builder.ai",
    "T-Mobile",
  ],
} as const;

export const navLinks = [
  { href: "#about", label: "About" },
  { href: "#skills", label: "Skills" },
  { href: "#experience", label: "Experience" },
  { href: "#projects", label: "Projects" },
  { href: "#achievements", label: "Achievements" },
  { href: "#education", label: "Education" },
  { href: "#performance", label: "Performance" },
  { href: "#process", label: "Process" },
  { href: "#resume", label: "Resume" },
] as const;
